### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

// userId is generated, poll and vote lists are empty.
{
  "username": "user1",
  "email": "user1@example.com"
}

### List all users
GET http://localhost:8080/users

### Create another user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com"
}

### List all users
GET http://localhost:8080/users

### User 1 creates a poll
POST http://localhost:8080/polls
Content-Type: application/json

// pollId is generated
{
  "creator":
  {
    "userId": 1,
    "username": "user1",
    "email": "user1@gmail.com"
  },
  "question": "What is your favorite programming language?",
  "validUntil": "2024-12-31T23:59:59Z",
  "publishedAt": "2024-09-08T12:00:00Z",
  "options": [
    {
      "caption": "Java",
      "presentationOrder": 1
    },
    {
      "caption": "Python",
      "presentationOrder": 2
    }
  ]
}

### List polls
GET http://localhost:8080/polls

### User2 votes on the poll
POST http://localhost:8080/users/2/votes
Content-Type: application/json

// voteId is generated
{
  "voter": {
    "userId": 2,
    "username": "user2",
    "email": "user2@gmail.com"
  },
  "option": {
    "optionId": 1,
    "caption": "Java",
    "presentationOrder": 1
  }
}

### User 2 changes his vote
PUT http://localhost:8080/users/2/votes/1
Content-Type: application/json

{
  "voteId": 1,
  "voter": {
    "userId": 2,
    "username": "user2",
    "email": "user2@gmail.com"
  },
  "option": {
    "optionId": 2,
    "caption": "Python",
    "presentationOrder": 2
  }
}

### List user 2 votes
GET http://localhost:8080/users/2/votes

### Delete user 2
DELETE http://localhost:8080/polls/1

### List user 2 votes
GET http://localhost:8080/users/2/votes





